### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by jayawasthi** [oddhill/node-bankid#34]
If was working perfectly but its started giving error from tomorrow. Can you please help 

I have mentioned the error below. Its working fine in case of authenticate but when we try to collect using the collect method then it gives the error. 

{name: 'BankIDError',
  message: undefined,
  code: 'internalError' }

@oddhill/bankid/lib/BankIDService.js:176:12)
![Screenshot from 2020-04-13 00-52-28](https://user-images.githubusercontent.com/7382779/79077720-223c6e80-7d21-11ea-8947-264496223a68.png)

**Comment by NormySan** [comment]
Hey, I'm not sure that the problem could be. I'll let you know if I get the same thing in any of my own apps using the module and any potential solutions.

**Comment by jayawasthi** [comment]
Hey,
I have figured out the issue its because of the test server was down. 
I have faced the same issue two days back then I try to test on the https://test.bankid.com/ but that server was also not responding.

There is no issue with the code.

Thanks

**Comment by NormySan** [comment]
Great, sorry that I never got around to answering again after my last reply.
