### ISSUE TITLE
Error: Cannot find module 'soap'

### ISSUE THREAD

**Issue by mathiasm74** [oddhill/node-bankid#5]
Trying to run your ```example/index.js```

The ```README.md``` says to install the ```node-soap``` model, but your ```BankID.js``` file calls ```require('soap')```, resulting in a ```Error: Cannot find module 'soap'``` error. Even if I change your code to ```require('node-soap')``` I get an error (```TypeError: soap.createClient is not a function```).

Is your code and/or documentation broken, or am I missing something?

**Comment by NormySan** [comment]
It should require the soap module and not node-soap, I'll fix the readme and package.json ASAP.

**Comment by mathiasm74** [comment]
> It should require the soap module and not node-soap, I'll fix the readme and package.json ASAP.

Yeah, should have guessed that was the reason... Thanks!
